/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vision;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Anriu Oliveira
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeCadastro = new javax.swing.JTextField();
        txtEmailCadastro = new javax.swing.JTextField();
        txtSenhaCadastro = new javax.swing.JPasswordField();
        lblCadastro = new javax.swing.JLabel();
        botaoCadastro1 = new javax.swing.JButton();
        txtRepetirSenhaCadastro = new javax.swing.JPasswordField();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1260, 726));

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtNomeCadastro.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        txtNomeCadastro.setForeground(new java.awt.Color(153, 153, 153));
        txtNomeCadastro.setText("Nome"); // NOI18N
        txtNomeCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txtNomeCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCadastroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeCadastroFocusLost(evt);
            }
        });
        txtNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCadastroActionPerformed(evt);
            }
        });
        txtNomeCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeCadastroKeyPressed(evt);
            }
        });

        txtEmailCadastro.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        txtEmailCadastro.setForeground(new java.awt.Color(153, 153, 153));
        txtEmailCadastro.setText("Email"); // NOI18N
        txtEmailCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txtEmailCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailCadastroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailCadastroFocusLost(evt);
            }
        });
        txtEmailCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailCadastroKeyPressed(evt);
            }
        });

        txtSenhaCadastro.setForeground(new java.awt.Color(153, 153, 153));
        txtSenhaCadastro.setText("Senha");
        txtSenhaCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txtSenhaCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaCadastroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaCadastroFocusLost(evt);
            }
        });
        txtSenhaCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaCadastroKeyPressed(evt);
            }
        });

        lblCadastro.setBackground(new java.awt.Color(0, 0, 0));
        lblCadastro.setFont(new java.awt.Font("NSimSun", 0, 40)); // NOI18N
        lblCadastro.setText("CADASTRO");

        botaoCadastro1.setBackground(new java.awt.Color(51, 51, 255));
        botaoCadastro1.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        botaoCadastro1.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastro1.setText("CADASTRAR");

        txtRepetirSenhaCadastro.setForeground(new java.awt.Color(153, 153, 153));
        txtRepetirSenhaCadastro.setText("Repetir Senha");
        txtRepetirSenhaCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txtRepetirSenhaCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRepetirSenhaCadastroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRepetirSenhaCadastroFocusLost(evt);
            }
        });
        txtRepetirSenhaCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRepetirSenhaCadastroKeyPressed(evt);
            }
        });

        botaoVoltar.setBackground(new java.awt.Color(51, 51, 255));
        botaoVoltar.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        botaoVoltar.setText("VOLTAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(lblCadastro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(139, 139, 139))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmailCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                                        .addComponent(txtSenhaCadastro)
                                        .addComponent(txtRepetirSenhaCadastro))
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(263, 263, 263))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(796, Short.MAX_VALUE)
                    .addComponent(botaoCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(261, 261, 261)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txtSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtRepetirSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(botaoVoltar)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(458, Short.MAX_VALUE)
                    .addComponent(botaoCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(272, 272, 272)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCadastroActionPerformed

    private void txtNomeCadastroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCadastroFocusGained
        if(txtNomeCadastro.getText().equals("Nome")){
            txtNomeCadastro.setCaretPosition(0);
            txtNomeCadastro.setCaretColor(Color.BLACK);
        } else{
            txtNomeCadastro.setSelectionStart(0);
        }
    }//GEN-LAST:event_txtNomeCadastroFocusGained

    private void txtNomeCadastroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCadastroFocusLost
        if(txtNomeCadastro.getText().equals("")){
            txtNomeCadastro.setText("Nome");
            txtNomeCadastro.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtNomeCadastroFocusLost

    private void txtNomeCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCadastroKeyPressed
        if(txtNomeCadastro.getText().equals("Nome")){
            txtNomeCadastro.setText("");
            txtNomeCadastro.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNomeCadastroKeyPressed

    private void txtSenhaCadastroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaCadastroFocusGained
        if(txtSenhaCadastro.getText().equals("Senha")){
            txtSenhaCadastro.setCaretPosition(0);
            txtSenhaCadastro.setCaretColor(Color.BLACK);
        } else{
            txtSenhaCadastro.setSelectionStart(0);
        }
    }//GEN-LAST:event_txtSenhaCadastroFocusGained

    private void txtSenhaCadastroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaCadastroFocusLost
        if(txtSenhaCadastro.getText().equals("")){
            txtSenhaCadastro.setEchoChar((char) 0);
            txtSenhaCadastro.setText("Senha");
            txtSenhaCadastro.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSenhaCadastroFocusLost

    private void txtEmailCadastroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailCadastroFocusGained
        if(txtEmailCadastro.getText().equals("Email")){
            txtEmailCadastro.setCaretPosition(0);
            txtEmailCadastro.setCaretColor(Color.BLACK);
        } else{
            txtEmailCadastro.setSelectionStart(0);
        }
    }//GEN-LAST:event_txtEmailCadastroFocusGained

    private void txtEmailCadastroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailCadastroFocusLost
        if(txtEmailCadastro.getText().equals("")){
            txtEmailCadastro.setText("Email");
            txtEmailCadastro.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtEmailCadastroFocusLost

    private void txtSenhaCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaCadastroKeyPressed
        if(txtSenhaCadastro.getText().equals("Senha")){
            txtSenhaCadastro.setText("");
            txtSenhaCadastro.setForeground(Color.BLACK);
            txtSenhaCadastro.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_txtSenhaCadastroKeyPressed

    private void txtEmailCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailCadastroKeyPressed
        if(txtEmailCadastro.getText().equals("Email")){
            txtEmailCadastro.setText("");
            txtEmailCadastro.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEmailCadastroKeyPressed

    private void txtRepetirSenhaCadastroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRepetirSenhaCadastroFocusGained
        if(txtRepetirSenhaCadastro.getText().equals("Repetir Senha")){
            txtRepetirSenhaCadastro.setCaretPosition(0);
            txtRepetirSenhaCadastro.setCaretColor(Color.BLACK);
        } else{
            txtRepetirSenhaCadastro.setSelectionStart(0);
        }
    }//GEN-LAST:event_txtRepetirSenhaCadastroFocusGained

    private void txtRepetirSenhaCadastroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRepetirSenhaCadastroFocusLost
       if(txtRepetirSenhaCadastro.getText().equals("")){
            txtRepetirSenhaCadastro.setEchoChar((char) 0);
            txtRepetirSenhaCadastro.setText("Repetir Senha");
            txtRepetirSenhaCadastro.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtRepetirSenhaCadastroFocusLost

    private void txtRepetirSenhaCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepetirSenhaCadastroKeyPressed
        if(txtRepetirSenhaCadastro.getText().equals("Repetir Senha")){
            txtRepetirSenhaCadastro.setText("");
            txtRepetirSenhaCadastro.setForeground(Color.BLACK);
            txtRepetirSenhaCadastro.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_txtRepetirSenhaCadastroKeyPressed



    public JTextField getTxtEmailCadastro() {
        return txtEmailCadastro;
    }

    
    public JTextField getTxtEmailLogin2() {
        return txtEmailCadastro;
    }

    public JPasswordField getTxtSenhaCadastro() {
        return txtSenhaCadastro;
    }

    public JButton getBotaoCadastro1() {
        return botaoCadastro1;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

   

    public JTextField getTxtUsuarioCadastro() {
        return txtNomeCadastro;
    }

    public JTextField getTxtNomeCadastro() {
        return txtNomeCadastro;
    }

    public JPasswordField getTxtRepetirSenhaCadastro() {
        return txtRepetirSenhaCadastro;
    }
    
    

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro1;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JTextField txtEmailCadastro;
    private javax.swing.JTextField txtNomeCadastro;
    private javax.swing.JPasswordField txtRepetirSenhaCadastro;
    private javax.swing.JPasswordField txtSenhaCadastro;
    // End of variables declaration//GEN-END:variables
    

}
