/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vision;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Anriu Oliveira
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCadastro
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoRecup = new javax.swing.JButton();
        botaoCadastro = new javax.swing.JButton();
        lblLogin1 = new javax.swing.JLabel();
        txtEmailLogin = new javax.swing.JTextField();
        txtSenhaLogin1 = new javax.swing.JPasswordField();
        botaoLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1260, 726));
        setMinimumSize(new java.awt.Dimension(1260, 726));
        setPreferredSize(new java.awt.Dimension(1260, 726));

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        botaoRecup.setBackground(new java.awt.Color(51, 51, 255));
        botaoRecup.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        botaoRecup.setForeground(new java.awt.Color(255, 255, 255));
        botaoRecup.setText("RECUPERAR SENHA");

        botaoCadastro.setBackground(new java.awt.Color(51, 51, 255));
        botaoCadastro.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        botaoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastro.setText("CADASTRAR");
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        lblLogin1.setBackground(new java.awt.Color(0, 0, 0));
        lblLogin1.setFont(new java.awt.Font("NSimSun", 0, 40)); // NOI18N
        lblLogin1.setText("LOGIN");

        txtEmailLogin.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        txtEmailLogin.setForeground(new java.awt.Color(153, 153, 153));
        txtEmailLogin.setText("Email"); // NOI18N
        txtEmailLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txtEmailLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailLoginFocusLost(evt);
            }
        });
        txtEmailLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailLoginKeyPressed(evt);
            }
        });

        txtSenhaLogin1.setForeground(new java.awt.Color(153, 153, 153));
        txtSenhaLogin1.setText("Senha");
        txtSenhaLogin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txtSenhaLogin1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaLogin1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaLogin1FocusLost(evt);
            }
        });
        txtSenhaLogin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaLogin1KeyPressed(evt);
            }
        });

        botaoLogin.setBackground(new java.awt.Color(51, 51, 255));
        botaoLogin.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        botaoLogin.setForeground(new java.awt.Color(255, 255, 255));
        botaoLogin.setText("ENTRAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailLogin)
                            .addComponent(txtSenhaLogin1)
                            .addComponent(botaoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoRecup, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 188, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtSenhaLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRecup, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailLoginFocusGained
        if(txtEmailLogin.getText().equals("Email")){
            txtEmailLogin.setCaretPosition(0);
            txtEmailLogin.setCaretColor(Color.BLACK);
        } else{
            txtEmailLogin.setSelectionStart(0);
        }
    }//GEN-LAST:event_txtEmailLoginFocusGained

    private void txtEmailLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailLoginFocusLost
        if(txtEmailLogin.getText().equals("")){
            txtEmailLogin.setText("Email");
            txtEmailLogin.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtEmailLoginFocusLost

    private void txtEmailLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailLoginKeyPressed
        if(txtEmailLogin.getText().equals("Email")){
            txtEmailLogin.setText("");
            txtEmailLogin.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEmailLoginKeyPressed

    private void txtSenhaLogin1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaLogin1FocusGained
        if(txtSenhaLogin1.getText().equals("Senha")){
            txtSenhaLogin1.setCaretPosition(0);
            txtSenhaLogin1.setCaretColor(Color.BLACK);
        } else{
            txtSenhaLogin1.setSelectionStart(0);
        }
    }//GEN-LAST:event_txtSenhaLogin1FocusGained

    private void txtSenhaLogin1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaLogin1FocusLost
        if(txtSenhaLogin1.getText().equals("")){
            txtSenhaLogin1.setEchoChar((char) 0);
            txtSenhaLogin1.setText("Senha");
            txtSenhaLogin1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSenhaLogin1FocusLost

    private void txtSenhaLogin1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaLogin1KeyPressed
        if(txtSenhaLogin1.getText().equals("Senha")){
            txtSenhaLogin1.setText("");
            txtSenhaLogin1.setForeground(Color.BLACK);
            txtSenhaLogin1.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_txtSenhaLogin1KeyPressed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroActionPerformed

    public JButton getBotaoCadastro() {
        return botaoCadastro;
    }


    public JButton getBotaoLogin() {
        return botaoLogin;
    }

    public JButton getBotaoRecup() {
        return botaoRecup;
    }

   

    public JTextField getTxtEmailLogin() {
        return txtEmailLogin;
    }
 

   
    public JPasswordField getTxtSenhaLogin1() {
        return txtSenhaLogin1;
    }

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JButton botaoRecup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JPasswordField txtSenhaLogin1;
    // End of variables declaration//GEN-END:variables
    public void abrirAlerta(String titulo, String mensagem, int tipo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, tipo); 
    }
    
    public String openDialog(){
        return JOptionPane.showInputDialog(this, "Informe seu email:", 
                                            "Solicitação de Código de Recuperação",0);        
    }

}
